[Behaviour]
resumeplayback=true

[Player]
playback_playlist=1
playback_position=0
playback_state=2

[PlaylistSequence]
repeat_mode=0
shuffle_mode=1

[Subsonic]
authmethod=1
downloadalbumcovers=true
enabled=true
http2=false
password=ZGVtbw==
serversidescrobbling=false
url=@Variant(\0\0\0\x11\0\0\0\x1dhttp://www.dccathome.com:4533)
usealbumidforalbumcovers=false
username=demo
verifycertificate=true
